### ISSUE TITLE
About code

### ISSUE THREAD

**Issue by wenjie-li216** [B-Xi/TGRS_2020_MDN-ASP#1]
I find that there is no MDU_func in this repository and it is in main_MDN_ASP.py. And I find that there is no IndianTR_gt.mat in data/GRSM2018indian. I sincerely hope that you can help me. Thanks a lot.
师兄您好，我是西电智能院的学生。我发现仓库中没有MDU_func和IndianTR_gt.mat，您能帮忙解决一下这个问题吗？谢谢。

**Comment by B-Xi** [comment]
> I find that there is no MDU_func in this repository and it is in main_MDN_ASP.py. And I find that there is no IndianTR_gt.mat in data/GRSM2018indian. I sincerely hope that you can help me. Thanks a lot.
> 师兄您好，我是西电智能院的学生。我发现仓库中没有MDU_func和IndianTR_gt.mat，您能帮忙解决一下这个问题吗？谢谢。

I have uploaded the 'IndianTR_gt.mat' and the MDN_func can be referred to the MDN paper and the source code of SSRN: https://github.com/zilongzhong/SSRN. Besides, the complete 'MDN_func.py' will be released after my related works are published. Thank you.

**Comment by wenjie-li216** [comment]
> > I find that there is no MDU_func in this repository and it is in main_MDN_ASP.py. And I find that there is no IndianTR_gt.mat in data/GRSM2018indian. I sincerely hope that you can help me. Thanks a lot.
> > 师兄您好，我是西电智能院的学生。我发现仓库中没有MDU_func和IndianTR_gt.mat，您能帮忙解决一下这个问题吗？谢谢。
> 
> I have uploaded the 'IndianTR_gt.mat' and the MDN_func can be referred to the MDN paper and the source code of SSRN: https://github.com/zilongzhong/SSRN. Besides, the complete 'MDN_func.py' will be released after my related works are published. Thank you.

Thank you very much.
