### ISSUE TITLE
 'main'_ MDN_ ASP. Py ' seems to be a missing function MDN_ func

### ISSUE THREAD

**Issue by hmk5735** [B-Xi/TGRS_2020_MDN-ASP#2]
作者你好，感谢你的贡献，但是我在运行‘main_MDN_ASP.py ’是，系统提示‘ModuleNotFoundError: No module named 'MDN_func'’，我想似乎缺少一个函数MDN_func。如果能帮我解决的真的是太感谢了，我的邮箱是573515641@qq.com.再次谢谢您的开源。
Hello, author, thank you for your contribution, but I'm running 'main'_ MDN_ ASP. Py 'yes, the system prompts' modulenotfounderror: no module named' MDN_ Func ', I think there seems to be a missing function MDN_ func。 Thank you very much if you can help me solve it. My email is 573515641@qq.com. Thank you again for your open source

**Comment by B-Xi** [comment]
I have open-sourced the MDN_ Func.py.

**Comment by hmk5735** [comment]
Thank you！
